### ISSUE TITLE
snappy-java v1.1.10.8 breaks on non-Alpine systems with musl installed

### ISSUE THREAD

**Issue by srstsavage** [ERDDAP/erddap#544]
FYI, the version of snappy-java currently in use (v1.1.10.8) has a nasty bug on non-Alpine systems with `musl` installed:

https://github.com/xerial/snappy-java/issues/692

Hopefully fixed at some point, but it's a fairly significant bug with a seemingly simple fix that's been open almost a year...

**Comment by ChrisJohnNOAA** [comment]
Should we downgrade to 1.1.10.7?

Also I believe we only indirectly use it through Cassandra (and maybe Parquet - but we could easily use different compression in Parquet).

My understanding is Snappy is optional for Cassandra, and without it Cassandra could use an alternative compression (lz4 which we already have the dependency included for).

**Comment by rmendels** [comment]
@ChrisJohnNOAA @srstsavage  See the closed issue #463.  There I write:

okay this took me forever to resolve, and should be noted in case others run into it.

problem: snappy-java 1.1.10.8 incorrectly selects musl binary on Ubuntu 22.04 (Jammy) with glibc

On Ubuntu 22.04 LTS (Jammy, glibc 2.35) with Java 25 (Temurin-25.0.1+8), snappy-java 1.1.10.8 incorrectly extracts and attempts to load Linux/x86_64-musl/libsnappyjava.so instead of Linux/x86_64/libsnappyjava.so, causing:

NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy

Environment:

OS: Ubuntu 22.04.5 LTS (Jammy), glibc 2.35
JVM: OpenJDK Temurin-25.0.1+8 64-bit
snappy-java: 1.1.10.8
The same jar works correctly on Ubuntu 24.04.4 LTS (Noble) with the same JVM

Evidence:

ldd on the extracted .so shows libc.musl-x86_64.so.1 => not found
Manually forcing Linux/x86_64/libsnappyjava.so via -Dorg.xerial.snappy.lib.path resolves the issue
The glibc binary (Linux/x86_64/libsnappyjava.so) links correctly against libc.so.6 on this system

Workaround to be added to $JAVA_OPTS:
bash-Dorg.xerial.snappy.lib.path=/path/to/Linux/x86_64
-Dorg.xerial.snappy.lib.name=libsnappyjava.so

I actually extracted the correct .so, put in a separate directory in $TOMCAT/temp, and then set that in the JAVA_OPTS.

**Comment by srstsavage** [comment]
Ah, so Roy has seen this monster already. I think my main concern is that users who encounter this fairly confusing error know how to identify and remediate. Maybe monitoring the mailing list is enough...

As far as downgrading to `v1.1.10.7` until a fix is released...maybe? `org.xerial.snappy:snappy-java` itself appears to have no Java dependencies. This is the change set between `v1.1.10.7` and `v1.1.10.8`.

https://github.com/xerial/snappy-java/compare/v1.1.10.7...v1.1.10.8
