### ISSUE TITLE
Parquet Write fails for Gridded Datasets

### ISSUE THREAD

**Issue by rmendels** [ERDDAP/erddap#463]
**Describe the bug**
Writing Parquet files fails from griddap,  works with tabledap.  It produces the error:

Error {
    code=500;
    message="Internal Server Error: NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy";
}

**To Reproduce**
1. Go to any gridded dataset,  say https://coastwatch.pfeg.noaa.gov/erddap/griddap/charmForecast3day.html and choose any small download.  
2. Set file type to parquet
3. See error

**Expected behavior**
Successful download

**Screenshots**

**Server**
- What ERDDAP™ server? If you're the admin, please provide what version of ERDDAP™, Tomcat, and Java you are using.
https://coastwatch.pfeg.noaa.gov/erddap

**Desktop (please complete the following information):**

**Additional context**
I ran into this working on adding parquet to my R package

I asked Claude for possible causes of this,  it said:

```
ERDDAP is trying to write the parquet file using Snappy compression, but the Snappy native library (snappy-java) isn't loading properly in the JVM. This is a known issue with snappy-java — it bundles native .so/.dll files that get extracted to a temp directory at runtime, and that can fail due to:

Architecture mismatch — the snappy-java jar was built for a different platform/arch than the JVM running ERDDAP (common on newer ARM servers or mixed environments)
Temp directory not executable — the JVM tries to extract the native lib to /tmp but the filesystem is mounted noexec
Class loader isolation — if ERDDAP is running in a container or with a restricted security policy

```

**Comment by rmendels** [comment]
Works on other ERDDAP™s,  don't know why it fails here.  I have to do a total server restart tomorrow will test re-installing the ERDDAP™

**Comment by rmendels** [comment]
okay this took me forever to resolve,  and should be noted in case others run into it.

problem:  snappy-java 1.1.10.8 incorrectly selects musl binary on Ubuntu 22.04 (Jammy) with glibc

On Ubuntu 22.04 LTS (Jammy, glibc 2.35) with Java 25 (Temurin-25.0.1+8), snappy-java 1.1.10.8 incorrectly extracts and attempts to load Linux/x86_64-musl/libsnappyjava.so instead of Linux/x86_64/libsnappyjava.so, causing:

NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy

Environment:

OS: Ubuntu 22.04.5 LTS (Jammy), glibc 2.35
JVM: OpenJDK Temurin-25.0.1+8 64-bit
snappy-java: 1.1.10.8
The same jar works correctly on Ubuntu 24.04.4 LTS (Noble) with the same JVM

Evidence:

ldd on the extracted .so shows libc.musl-x86_64.so.1 => not found
Manually forcing Linux/x86_64/libsnappyjava.so via -Dorg.xerial.snappy.lib.path resolves the issue
The glibc binary (Linux/x86_64/libsnappyjava.so) links correctly against libc.so.6 on this system

Workaround to be added to $JAVA_OPTS:
bash-Dorg.xerial.snappy.lib.path=/path/to/Linux/x86_64
-Dorg.xerial.snappy.lib.name=libsnappyjava.so

I actually extracted the correct .so,  put in a separate directory in $TOMCAT/temp,  and then set that in the JAVA_OPTS.
